-- ============================================================
-- supabase/seed.sql — GENERATED by scripts/gen-seed-sql.mjs. DO NOT HAND-EDIT.
--
--   node scripts/gen-seed-sql.mjs
--
-- Generated from packages/core/lib/seedData.js. All timestamps are now()-relative
-- intervals, so the demo data is always fresh as of the moment this file runs.
-- Re-run it any time the demo has gone stale.
--
-- Idempotent: truncates every app table first (restart identity, cascade).
-- ============================================================
begin;

truncate table
  access_requests, post_templates, media_assets, review_replies, reviews,
  call_transcript_turns, calls, customer_notes, customer_timeline_events,
  customers, managers, stores, dealers
restart identity cascade;

-- ---------------- dealers ----------------
insert into dealers (id, phone, name) values
  ('dlr-01', '9845012342', 'Lakshmi Electronics (Rajesh Kumar)'),
  ('dlr-02', '9845077777', 'Lakshmi Electronics (Jayanagar owner)'),
  ('dlr-03', '9845088888', 'CRM Departmental Stores');

-- ---------------- stores (the store-code registry; rich rows for the primary dealer's three) ----------------
insert into stores (id, dealer_id, store_code, seq, name, branch, city, address, pincode, state, landmark, stated_lat, stated_lng, actual_lat, actual_lng, rating, reviews_count, verified, verified_at, missed_count, answered_count, recovered_count, recovery_pct, health, health_prev, is_primary, added_ago, added_ago_key, added_at) values
  ('lks-ind', 'dlr-01', 'LKS-IND-01', 1, 'Lakshmi Electronics', 'Indiranagar', 'Bangalore', '127, 100 Feet Road, Indiranagar, Bangalore', '560038', 'Karnataka', 'Opposite Sony Centre', 12.9719, 77.6412, 12.9719, 77.6412, 4.6, 38, true, now(), 7, 14, 5, 71, 82, 86, true, 'Original store', 'seed.location.addedOriginal', null),
  ('lks-kor', 'dlr-01', 'LKS-KOR-02', 2, 'Lakshmi Electronics', 'Koramangala', 'Bangalore', '80 Feet Road, 4th Block, Koramangala, Bangalore', '560034', 'Karnataka', 'Near Forum Mall', 12.9352, 77.6245, 12.9366, 77.626, 4.5, 22, false, null, 11, 9, 5, 45, 61, 66, false, 'Added 2 weeks ago', 'seed.location.addedWhen', now() + ((-1209600000) || ' milliseconds')::interval),
  ('lks-new', 'dlr-01', 'LKS-HSR-03', 3, 'Lakshmi Electronics', 'HSR Layout', 'Bandra', 'Sector 27, HSR Layout, Bandra, Haryana', '201301', 'Haryana', '', 12.9116, 77.6389, 12.9101, 77.6377, 4.4, 18, false, null, 5, 12, 5, 74, 48, 51, false, 'Added 3 days ago', 'seed.location.addedWhen', now() + ((-259200000) || ' milliseconds')::interval),
  ('lks-jay', 'dlr-02', 'LKS-JAY-04', 4, 'Lakshmi Electronics', 'Jayanagar', 'Bangalore', null, null, null, null, null, null, null, null, null, null, false, null, null, null, null, null, null, null, false, null, null, null),
  ('crm-kor', 'dlr-03', 'CRM-KOR-01', 5, 'CRM Departmental Stores', 'Koramangala', 'Bangalore', null, null, null, null, null, null, null, null, null, null, false, null, null, null, null, null, null, null, false, null, null, null);

-- ---------------- managers ----------------
insert into managers (id, dealer_id, name, initials, role, phone) values
  ('u1', 'dlr-01', 'Rajesh Kumar', 'RK', 'manager', '+91 98•••••342'),
  ('u2', 'dlr-01', 'Vikram Shetty', 'VS', null, null),
  ('u3', 'dlr-01', 'Priya Nair', 'PN', null, null);

-- ---------------- customers ----------------
insert into customers (id, store_id, seq, name, phone, cli, band, value, category, category_key, ai_guess, ai_guess_key, first_seen_label, first_seen_at, last_seen_label, last_seen_at, call_count, review_sent, reviewed) values
  ('cust-231', 'lks-ind', 1, null, '9880142231', 92, 'hot', 38000, 'Air Conditioner', 'seed.category.airConditioner', 'Lives near the store · weekday daytime caller · likely a homeowner ready to buy · prefers EMI', 'seed.aiGuess.nearbyHomeownerEmi', 'Today · 9:34 AM', now() + ((-8760000) || ' milliseconds')::interval, '12 min ago', now() + ((-720000) || ' milliseconds')::interval, 3, false, false),
  ('cust-087', 'lks-ind', 2, null, '7899310087', 86, 'hot', 52000, 'Smart TV', 'seed.category.smartTv', 'Saw the Times of India ad · called within 4 min · high purchase intent', 'seed.aiGuess.toiAdHighIntent', 'Today · 11:22 AM', now() + ((-2280000) || ' milliseconds')::interval, '38 min ago', now() + ((-2280000) || ' milliseconds')::interval, 1, false, false),
  ('cust-988', 'lks-ind', 3, null, '9845236988', 88, 'hot', 45000, 'Air Conditioner', 'seed.category.airConditioner', 'Repeat shopper · prefers Samsung · happy in conversation · wants EMI', 'seed.aiGuess.repeatSamsungEmi', 'Today · 12:14 PM', now() + ((-360000) || ' milliseconds')::interval, '6 min ago', now() + ((-360000) || ' milliseconds')::interval, 1, false, false),
  ('cust-775', 'lks-ind', 4, 'Anand Rao', '9886054775', 95, 'hot', 32500, 'Washing Machine', 'seed.category.washingMachine', 'Repeat customer · already bought once · loyal · brings family along', 'seed.aiGuess.loyalRepeatFamily', 'Yesterday 6:48 PM', now() + ((-66360000) || ' milliseconds')::interval, 'Yesterday 7:14 PM', now() + ((-64800000) || ' milliseconds')::interval, 1, true, true),
  ('cust-554', 'lks-ind', 5, null, '9740118554', 78, 'hot', 21000, 'Refrigerator', 'seed.category.refrigerator', 'Returning caller · came back next day · serious about buying', 'seed.aiGuess.returningNextDay', 'Yesterday 6:12 PM', now() + ((-64080000) || ' milliseconds')::interval, '64 min ago', now() + ((-3840000) || ' milliseconds')::interval, 2, false, false),
  ('cust-019', 'lks-ind', 6, 'Prakash Menon', '9448027019', 28, 'cold', 0, 'Service', 'seed.category.service', 'Upset existing customer · warranty service complaint · needs care', 'seed.aiGuess.upsetWarranty', 'Last month', now() + ((-2764800000) || ' milliseconds')::interval, '2h ago', now() + ((-7200000) || ' milliseconds')::interval, 4, false, false),
  ('cust-445', 'lks-ind', 7, null, '9663380445', 81, 'hot', 110000, 'Smart TV', 'seed.category.smartTv', 'Premium buyer · 55" OLED interest · social-ad warmed · weekend shopper', 'seed.aiGuess.premiumOledWeekend', 'Today · 10:24 AM', now() + ((-6960000) || ' milliseconds')::interval, '78 min ago', now() + ((-4680000) || ' milliseconds')::interval, 2, false, false),
  ('cust-512', 'lks-ind', 8, 'Divya K.', '8095471512', 68, 'warm', 24000, 'Headphones', 'seed.category.headphones', 'Younger buyer · price-sensitive · Facebook offer brought her in', 'seed.aiGuess.youngPriceSensitive', 'Today · 9:34 AM', now() + ((-9960000) || ' milliseconds')::interval, '166 min ago', now() + ((-9960000) || ' milliseconds')::interval, 1, true, false),
  ('cust-231b', 'lks-ind', 9, null, '9739260231', 56, 'warm', 34000, 'Refrigerator', 'seed.category.refrigerator', 'Comparing with online prices · wants the exchange quote held · deciding with family', 'seed.aiGuess.comparingExchangeFamily', 'Today · 10:48 AM', now() + ((-5520000) || ' milliseconds')::interval, '92 min ago', now() + ((-5520000) || ' milliseconds')::interval, 1, false, false),
  ('cust-208', 'lks-ind', 10, 'Nagaraj B.', '9611472208', 22, 'cold', 0, 'Service', 'seed.category.service', 'Already bought · delivery missed twice · wants a date he can trust', 'seed.aiGuess.deliveryMissedTrust', '4 days ago', now() + ((-345600000) || ' milliseconds')::interval, '4 days ago', now() + ((-345600000) || ' milliseconds')::interval, 1, false, false),
  ('cust-372', 'lks-ind', 11, 'Imran Qureshi', '9900863372', 26, 'cold', 0, 'Service', 'seed.category.service', 'Charged for a warranty repair by mistake · refund promised · wants a senior technician', 'seed.aiGuess.warrantyOverchargedRefund', '18 days ago', now() + ((-1555200000) || ' milliseconds')::interval, '18 days ago', now() + ((-1555200000) || ' milliseconds')::interval, 1, false, false);

-- ---------------- customer timeline ----------------
insert into customer_timeline_events (customer_id, seq, type, at_label, at, at_precision, detail, detail_key) values
  ('cust-231', 1, 'missed', '9:34 AM today', now() + ((-8760000) || ' milliseconds')::interval, null, 'First missed call via SingleInterface', 'seed.timeline.firstMissedSi'),
  ('cust-231', 2, 'missed', '10:42 AM today', now() + ((-4680000) || ' milliseconds')::interval, null, 'Second missed call · same number', 'seed.timeline.secondMissedSameNumber'),
  ('cust-231', 3, 'missed', '11:48 AM today', now() + ((-720000) || ' milliseconds')::interval, null, 'Third missed call · still trying', 'seed.timeline.thirdMissedStillTrying'),
  ('cust-087', 1, 'missed', '11:22 AM today', now() + ((-2280000) || ' milliseconds')::interval, null, 'Missed call · Times of India campaign', 'seed.timeline.missedToiCampaign'),
  ('cust-988', 1, 'inbound', '12:14 PM today', now() + ((-360000) || ' milliseconds')::interval, null, 'Answered call · 4m 32s · Samsung AC enquiry', 'seed.timeline.answeredSamsungAc'),
  ('cust-775', 1, 'missed', 'Yesterday 6:48 PM', now() + ((-66360000) || ' milliseconds')::interval, null, 'Missed call · SingleInterface', 'seed.timeline.missedSi'),
  ('cust-775', 2, 'outbound', 'Yesterday 7:14 PM', now() + ((-64800000) || ' milliseconds')::interval, null, 'Called back · 5m 21s · sale closed ₹32,500', 'seed.timeline.calledBackSaleClosed'),
  ('cust-775', 3, 'review-sent', 'Yesterday 8:02 PM', now() + ((-61920000) || ' milliseconds')::interval, null, 'Review link sent on WhatsApp', 'seed.timeline.reviewLinkSent'),
  ('cust-775', 4, 'review-landed', 'Today 9:18 AM', now() + ((-14160000) || ' milliseconds')::interval, null, '5★ review on Google', 'seed.timeline.reviewLandedGoogle'),
  ('cust-554', 1, 'missed', 'Yesterday 6:12 PM', now() + ((-64080000) || ' milliseconds')::interval, null, 'Missed call · Google', 'seed.timeline.missedGoogle'),
  ('cust-554', 2, 'missed', '10:56 AM today', now() + ((-3840000) || ' milliseconds')::interval, null, 'Tried again · still not picked', 'seed.timeline.triedAgainNotPicked'),
  ('cust-019', 1, 'inbound', 'Last month · 14 Dec', now() + ((-2764800000) || ' milliseconds')::interval, 'relative', 'Bought AC ₹42,000', 'seed.timeline.boughtAc'),
  ('cust-019', 2, 'inbound', 'Last week', now() + ((-691200000) || ' milliseconds')::interval, 'relative', 'First service complaint', 'seed.timeline.firstServiceComplaint'),
  ('cust-019', 3, 'outbound', '10:11 AM today', now() + ((-7740000) || ' milliseconds')::interval, null, 'Called back · 1m 04s · escalated to service', 'seed.timeline.calledBackEscalated'),
  ('cust-445', 1, 'missed', '10:24 AM today', now() + ((-6960000) || ' milliseconds')::interval, null, 'Missed call · Times of India', 'seed.timeline.missedToi'),
  ('cust-445', 2, 'outbound', '11:02 AM today', now() + ((-4680000) || ' milliseconds')::interval, null, 'Called back · 2m 11s · catalog sent on WhatsApp', 'seed.timeline.calledBackCatalogSent'),
  ('cust-512', 1, 'inbound', '9:34 AM today', now() + ((-9960000) || ' milliseconds')::interval, null, 'Answered call · 1m 47s · Sony WH-1000XM5', 'seed.timeline.answeredSony'),
  ('cust-512', 2, 'review-sent', '10:12 AM today', now() + ((-7680000) || ' milliseconds')::interval, null, 'Review link sent on WhatsApp', 'seed.timeline.reviewLinkSent'),
  ('cust-231b', 1, 'inbound', '10:48 AM today', now() + ((-5520000) || ' milliseconds')::interval, null, 'Answered call · 3m 58s · double-door fridge under ₹40K', 'seed.timeline.answeredFridgeComparing'),
  ('cust-208', 1, 'inbound', '4 days ago', now() + ((-345600000) || ' milliseconds')::interval, 'relative', 'Answered call · 2m 44s · chasing a late washing-machine delivery', 'seed.timeline.answeredDeliveryChase'),
  ('cust-372', 1, 'outbound', '18 days ago', now() + ((-1555200000) || ' milliseconds')::interval, 'relative', 'Called back · 3m 38s · refrigerator still not cooling', 'seed.timeline.calledBackFridgeComplaint');

-- ---------------- customer notes ----------------
insert into customer_notes (id, customer_id, author, body, at) values
  ('nt-231-1', 'cust-231', 'Rajesh Kumar', 'Rang three times before noon, never got through. Try him before 7 PM — likely calling on his commute.', now() + ((-600000) || ' milliseconds')::interval),
  ('nt-988-1', 'cust-988', 'Rajesh Kumar', 'Samsung 1.5T inverter 3-star held aside till Friday. Wants 6-month no-cost EMI. Old AC dead, so he is in a hurry — do not lose this one.', now() + ((-240000) || ' milliseconds')::interval),
  ('nt-775-1', 'cust-775', 'Rajesh Kumar', 'LG 7kg front load booked, ₹32,500, paying on delivery by card. HAL 2nd stage — free delivery zone.', now() + ((-64440000) || ' milliseconds')::interval),
  ('nt-775-2', 'cust-775', 'Rajesh Kumar', 'Delivery Saturday 10 AM confirmed on WhatsApp. Second purchase from us — wife’s sister is also a customer.', now() + ((-61800000) || ' milliseconds')::interval),
  ('nt-019-1', 'cust-019', 'Rajesh Kumar', 'Install booked 12th, team never turned up — twice. He took leave both days. I promised a service-desk call within 24h with a fixed slot. My name is on this now, follow it up myself.', now() + ((-7500000) || ' milliseconds')::interval),
  ('nt-019-2', 'cust-019', 'Rajesh Kumar', 'Do NOT send a review link to this number until the install is actually done.', now() + ((-7200000) || ' milliseconds')::interval),
  ('nt-445-1', 'cust-445', 'Rajesh Kumar', 'LG C-series 55" OLED, catalogue sent on WhatsApp. Deciding with his wife, coming Saturday before noon. Was comparing with the 2023 panel — hold the ₹1,09,990 price.', now() + ((-4440000) || ' milliseconds')::interval),
  ('nt-512-1', 'cust-512', 'Rajesh Kumar', 'Sony WH-1000XM5, quoted festive ₹24,990. Has a college ID — promised a case or stand as a sweetener, not a cash discount. Coming this weekend, ask for me at audio counter.', now() + ((-9600000) || ' milliseconds')::interval);

-- ---------------- calls (today's three buckets + history) ----------------
-- Seed customerIds with no CRM record are NULLed (app behavior identical):
--   mc-04 → cust-912
--   mc-05 → cust-446
--   mc-06 → cust-103
--   mc-07 → cust-770
--   mc-08 → cust-318
--   mc-09 → cust-602
insert into calls (id, store_id, customer_id, seq, bucket, outcome, spam, at, masked, full_masked_display, time_label, minutes_ago, source, duration, direction, cli, est_value, category, category_key, intent, intent_reason, intent_reason_key, repeats, repeat_history_labels, repeat_history_at, sentiment, mood, call_reason, call_reason_key, lead_status, review_link_sent, summary, summary_key, highlights, next_step, next_step_label, next_step_label_key, tag, ivr_stage, ivr_stage_key, ivr_dropped_at_label, ivr_dropped_at_key, ivr_dropped_after_sec, ivr_drop_reason, ivr_drop_reason_key) values
  ('mc-01', 'lks-ind', 'cust-231', 1, 'today', 'missed', false, now() + ((-720000) || ' milliseconds')::interval, '+91 •••••231', '+91 ●●●●● ●●231', '11:48 AM', 12, 'SingleInterface', null, null, 92, 38000, 'Air Conditioner', 'seed.category.airConditioner', 'high', 'Called 3 times in 2 hours — sounds urgent', 'seed.reason.urgentThreeCalls', 3, array['09:34 AM', '10:42 AM', '11:48 AM']::text[], array[now() + ((-8760000) || ' milliseconds')::interval, now() + ((-4680000) || ' milliseconds')::interval, now() + ((-720000) || ' milliseconds')::interval]::timestamptz[], 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-02', 'lks-ind', 'cust-087', 2, 'today', 'missed', false, now() + ((-2280000) || ' milliseconds')::interval, '+91 •••••087', '+91 ●●●●● ●●087', '11:22 AM', 38, 'Times of India', null, null, 86, 52000, 'Smart TV', 'seed.category.smartTv', 'high', 'Newspaper offer · called within 4 min of ad', 'seed.reason.newspaperAd', 1, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-03', 'lks-ind', 'cust-554', 3, 'today', 'missed', false, now() + ((-3840000) || ' milliseconds')::interval, '+91 •••••554', '+91 ●●●●● ●●554', '10:56 AM', 64, 'Google', null, null, 78, 21000, 'Refrigerator', 'seed.category.refrigerator', 'high', 'Same person called yesterday too', 'seed.reason.calledYesterdayToo', 2, array['Yesterday 6:12 PM', '10:56 AM']::text[], array[now() + ((-64080000) || ' milliseconds')::interval, now() + ((-3840000) || ' milliseconds')::interval]::timestamptz[], 'neutral', null, 'EMI options', 'seed.callReason.emiOptions', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-04', 'lks-ind', null, 4, 'today', 'missed', false, now() + ((-5700000) || ' milliseconds')::interval, '+91 •••••912', '+91 ●●●●● ●●912', '10:25 AM', 95, 'SingleInterface', null, null, 58, 14000, 'Washing Machine', 'seed.category.washingMachine', 'medium', 'First call · weekday morning', 'seed.reason.firstCallWeekday', 1, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-05', 'lks-ind', null, 5, 'today', 'missed', false, now() + ((-8520000) || ' milliseconds')::interval, '+91 •••••446', '+91 ●●●●● ●●446', '9:38 AM', 142, 'Facebook', null, null, 54, 9500, 'Headphones', 'seed.category.headphones', 'medium', 'Came from a Facebook offer', 'seed.reason.facebookOffer', 1, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-06', 'lks-ind', null, 6, 'today', 'missed', false, now() + ((-10680000) || ' milliseconds')::interval, '+91 •••••103', '+91 ●●●●● ●●103', '9:02 AM', 178, 'SingleInterface', null, null, 32, 4500, 'Accessories', 'seed.category.accessories', 'low', 'Hung up quickly · just looking around', 'seed.reason.hungUpQuickly', 1, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-07', 'lks-ind', null, 7, 'today', 'missed', false, now() + ((-12900000) || ' milliseconds')::interval, '+91 •••••770', '+91 ●●●●● ●●770', '8:25 AM', 215, 'Justdial', null, null, 64, 17500, 'Microwave', 'seed.category.microwave', 'medium', 'Tried Justdial yesterday and again today', 'seed.reason.justdialRepeat', 2, array['Yesterday 7:48 PM', '8:25 AM']::text[], array[now() + ((-58320000) || ' milliseconds')::interval, now() + ((-12900000) || ' milliseconds')::interval]::timestamptz[], 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-08', 'lks-ind', null, 8, 'today', 'missed', false, now() + ((-15360000) || ' milliseconds')::interval, '+91 •••••318', '+91 ●●●●● ●●318', '7:44 AM', 256, 'Google', null, null, 38, 6800, 'Browse', 'seed.category.browse', 'low', 'Early morning · just exploring', 'seed.reason.earlyMorning', 1, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('mc-09', 'lks-ind', null, 9, 'today', 'missed', true, now() + ((-18660000) || ' milliseconds')::interval, '+91 •••••602', '+91 ●●●●● ●●602', '6:49 AM', 311, 'SingleInterface', null, null, 12, 0, 'Spam?', 'seed.category.spam', 'low', 'Looks like spam · auto-flagged', 'seed.reason.looksLikeSpam', 1, null, null, 'neutral', null, 'Spam / unwanted', 'seed.callReason.spam', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('cc-01', 'lks-ind', 'cust-988', 10, 'today', 'answered', false, now() + ((-360000) || ' milliseconds')::interval, '+91 •••••988', null, '12:14 PM', 6, 'SingleInterface', '4m 32s', 'inbound', 88, null, null, null, null, null, null, null, null, null, 'positive', 'happy', 'EMI options', 'seed.callReason.emiOptions', 'open', false, 'Asked about Samsung 1.5T inverter AC. Wants EMI option. Will visit Friday between 5–7 PM.', 'seed.summary.samsungAcEmi', array['Wants Samsung 1.5T AC', 'Needs EMI', 'Coming Friday 5–7 PM']::text[], 'follow-up', 'Follow up Fri 4 PM', 'seed.nextStep.followUpFri', 'important', null, null, null, null, null, null, null),
  ('cc-02', 'lks-ind', 'cust-445', 11, 'today', 'answered', false, now() + ((-4680000) || ' milliseconds')::interval, '+91 •••••445', null, '11:02 AM', 78, 'Times of India', '2m 11s', 'outbound', 81, null, null, null, null, null, null, null, null, null, 'positive', 'happy', 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, 'Called back TOI ad lead. Wants 55" LG OLED. Sent catalog on WhatsApp. Visit Saturday morning.', 'seed.summary.lgOledCatalog', array['LG 55" OLED', 'Catalog sent on WhatsApp', 'Visit Sat morning']::text[], 'follow-up', 'Send catalog · already done', 'seed.nextStep.catalogSent', 'important', null, null, null, null, null, null, null),
  ('cc-03', 'lks-ind', 'cust-231b', 12, 'today', 'answered', false, now() + ((-5520000) || ' milliseconds')::interval, '+91 •••••231', null, '10:48 AM', 92, 'Google', '3m 58s', 'inbound', 56, null, null, null, null, null, null, null, null, null, 'neutral', 'okay', 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, 'Looking for a double-door fridge under ₹40K. Comparing brands. Will decide next week.', 'seed.summary.fridgeComparing', array['Budget ₹40K', 'Comparing brands', 'Decision next week']::text[], 'follow-up', 'Follow up Mon morning', 'seed.nextStep.followUpMon', null, null, null, null, null, null, null, null),
  ('cc-04', 'lks-ind', 'cust-019', 13, 'today', 'answered', false, now() + ((-7740000) || ' milliseconds')::interval, '+91 •••••019', null, '10:11 AM', 129, 'SingleInterface', '1m 04s', 'outbound', 28, null, null, null, null, null, null, null, null, null, 'negative', 'bad', 'Warranty / service', 'seed.callReason.warrantyService', 'open', false, 'Upset about delayed AC install from last month. Promised service desk callback within 24h.', 'seed.summary.acInstallDelay', array['Warranty issue', 'Service delayed', 'Escalated to service desk']::text[], 'important', 'Service follow-up · escalated', 'seed.nextStep.serviceEscalated', 'important', null, null, null, null, null, null, null),
  ('cc-05', 'lks-ind', 'cust-512', 14, 'today', 'answered', false, now() + ((-9960000) || ' milliseconds')::interval, '+91 •••••512', null, '9:34 AM', 166, 'Facebook', '1m 47s', 'inbound', 68, null, null, null, null, null, null, null, null, null, 'positive', 'happy', 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', true, 'Young buyer asked about Sony WH-1000XM5 headphones, wanted student discount. Visiting this weekend.', 'seed.summary.sonyHeadphones', array['Sony WH-1000XM5', 'Festive offer shared', 'Weekend visit']::text[], 'follow-up', 'Follow up Sat noon', 'seed.nextStep.followUpSat', null, null, null, null, null, null, null, null),
  ('cc-06', 'lks-ind', null, 15, 'today', 'answered', true, now() + ((-12480000) || ' milliseconds')::interval, '+91 •••••806', null, '8:52 AM', 208, 'Google', '0m 18s', 'inbound', 6, null, null, null, null, null, null, null, null, null, 'neutral', 'okay', 'Spam / unwanted', 'seed.callReason.spam', 'lost', false, 'Robotic voice · auto-marketing · almost certainly spam.', 'seed.summary.roboticSpam', array['Spam pattern auto-flagged']::text[], 'spam', 'Marked as spam', 'seed.nextStep.markedSpam', 'spam', null, null, null, null, null, null, null),
  ('cc-07', 'lks-ind', 'cust-775', 16, 'today', 'answered', false, now() + ((-64800000) || ' milliseconds')::interval, '+91 •••••775', null, 'Yesterday 7:14 PM', 1080, 'SingleInterface', '5m 21s', 'outbound', 95, null, null, null, null, null, null, null, null, null, 'positive', 'happy', 'Price enquiry', 'seed.callReason.priceEnquiry', 'converted', true, 'Sale done! LG washing machine ₹32,500. Delivery scheduled Saturday 10 AM.', 'seed.summary.saleClosedWasher', array['Sale closed ₹32,500', 'Saturday 10 AM delivery']::text[], 'important', 'Delivery confirmed', 'seed.nextStep.deliveryConfirmed', 'important', null, null, null, null, null, null, null),
  ('ivr-01', 'lks-ind', null, 17, 'today', 'ivr_drop', false, now() + ((-1320000) || ' milliseconds')::interval, '+91 •••••231', null, '11:38 AM', 22, 'SingleInterface', null, null, null, 26000, 'Air Conditioner', 'seed.category.airConditioner', null, null, null, null, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, null, null, null, null, null, null, null, 'Language menu', 'seed.ivr.stageLanguageMenu', 'After 8s', 'seed.ivr.droppedAfterSeconds', 8, 'Hung up while choosing language', 'seed.ivr.reasonChoosingLanguage'),
  ('ivr-02', 'lks-ind', null, 18, 'today', 'ivr_drop', false, now() + ((-3060000) || ' milliseconds')::interval, '+91 •••••409', null, '11:09 AM', 51, 'Google', null, null, null, 15000, 'Washing Machine', 'seed.category.washingMachine', null, null, null, null, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'open', false, null, null, null, null, null, null, null, 'Ring — no pickup', 'seed.ivr.stageRingNoPickup', 'After 30s', 'seed.ivr.droppedAfterSeconds', 30, 'IVR rang out, store did not connect', 'seed.ivr.reasonRangOut'),
  ('ivr-03', 'lks-ind', null, 19, 'today', 'ivr_drop', false, now() + ((-5280000) || ' milliseconds')::interval, '+91 •••••662', null, '10:32 AM', 88, 'Times of India', null, null, null, 41000, 'Smart TV', 'seed.category.smartTv', null, null, null, null, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'open', false, null, null, null, null, null, null, null, 'Store options menu', 'seed.ivr.stageStoreOptions', 'After 14s', 'seed.ivr.droppedAfterSeconds', 14, 'Dropped before selecting a store', 'seed.ivr.reasonBeforeStorePick'),
  ('ch-01', 'lks-ind', null, 20, 'history', 'missed', false, now() + ((-172800000) || ' milliseconds')::interval, '+91 •••••184', null, null, null, 'Google', null, null, 71, 34000, 'Air Conditioner', 'seed.category.airConditioner', 'high', null, null, null, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-02', 'lks-ind', null, 21, 'history', 'answered', false, now() + ((-162000000) || ' milliseconds')::interval, '+91 •••••627', null, null, null, 'SingleInterface', '3m 12s', 'inbound', 84, 61000, 'Smart TV', 'seed.category.smartTv', null, null, null, null, null, null, 'positive', null, 'EMI options', 'seed.callReason.emiOptions', 'converted', true, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-03', 'lks-ind', null, 22, 'history', 'missed', false, now() + ((-259200000) || ' milliseconds')::interval, '+91 •••••390', null, null, null, 'Justdial', null, null, 44, 19000, 'Refrigerator', 'seed.category.refrigerator', 'medium', null, null, null, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-04', 'lks-ind', 'cust-208', 23, 'history', 'answered', false, now() + ((-345600000) || ' milliseconds')::interval, '+91 •••••208', null, null, null, 'SingleInterface', '2m 44s', 'inbound', 22, 0, 'Service', 'seed.category.service', null, null, null, null, null, null, 'negative', null, 'Delivery delay', 'seed.callReason.deliveryDelay', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-05', 'lks-ind', null, 24, 'history', 'missed', false, now() + ((-432000000) || ' milliseconds')::interval, '+91 •••••741', null, null, null, 'Facebook', null, null, 39, 11000, 'Microwave', 'seed.category.microwave', 'low', null, null, null, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-06', 'lks-ind', null, 25, 'history', 'answered', false, now() + ((-518400000) || ' milliseconds')::interval, '+91 •••••053', null, null, null, 'Google', '4m 05s', 'inbound', 76, 41000, 'Air Conditioner', 'seed.category.airConditioner', null, null, null, null, null, null, 'positive', null, 'Installation request', 'seed.callReason.installationRequest', 'converted', true, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-07', 'lks-ind', null, 26, 'history', 'missed', false, now() + ((-777600000) || ' milliseconds')::interval, '+91 •••••466', null, null, null, 'Times of India', null, null, 68, 48000, 'Smart TV', 'seed.category.smartTv', 'medium', null, null, null, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-08', 'lks-ind', null, 27, 'history', 'answered', false, now() + ((-1036800000) || ' milliseconds')::interval, '+91 •••••815', null, null, null, 'Facebook', '1m 20s', 'inbound', 31, 8000, 'Headphones', 'seed.category.headphones', null, null, null, null, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-09', 'lks-ind', null, 28, 'history', 'missed', true, now() + ((-1209600000) || ' milliseconds')::interval, '+91 •••••900', null, null, null, 'SingleInterface', null, null, 8, 0, 'Spam?', 'seed.category.spam', 'low', null, null, null, null, null, 'neutral', null, 'Spam / unwanted', 'seed.callReason.spam', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-10', 'lks-ind', 'cust-372', 29, 'history', 'answered', false, now() + ((-1555200000) || ' milliseconds')::interval, '+91 •••••372', null, null, null, 'Google', '3m 38s', 'outbound', 26, 0, 'Service', 'seed.category.service', null, null, null, null, null, null, 'negative', null, 'Warranty / service', 'seed.callReason.warrantyService', 'open', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-11', 'lks-ind', null, 30, 'history', 'missed', false, now() + ((-1728000000) || ' milliseconds')::interval, '+91 •••••529', null, null, null, 'SingleInterface', null, null, 62, 36000, 'Air Conditioner', 'seed.category.airConditioner', 'medium', null, null, null, null, null, 'neutral', null, 'EMI options', 'seed.callReason.emiOptions', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-12', 'lks-ind', null, 31, 'history', 'answered', false, now() + ((-2160000000) || ' milliseconds')::interval, '+91 •••••118', null, null, null, 'Times of India', '6m 02s', 'outbound', 91, 88000, 'Smart TV', 'seed.category.smartTv', null, null, null, null, null, null, 'positive', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'converted', true, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-13', 'lks-ind', null, 32, 'history', 'missed', false, now() + ((-2764800000) || ' milliseconds')::interval, '+91 •••••677', null, null, null, 'Justdial', null, null, 49, 23000, 'Washing Machine', 'seed.category.washingMachine', 'medium', null, null, null, null, null, 'neutral', null, 'Stock availability', 'seed.callReason.stockAvailability', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-14', 'lks-ind', null, 33, 'history', 'answered', false, now() + ((-3456000000) || ' milliseconds')::interval, '+91 •••••245', null, null, null, 'SingleInterface', '2m 58s', 'inbound', 73, 39000, 'Air Conditioner', 'seed.category.airConditioner', null, null, null, null, null, null, 'positive', null, 'Installation request', 'seed.callReason.installationRequest', 'converted', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-15', 'lks-ind', null, 34, 'history', 'missed', false, now() + ((-4752000000) || ' milliseconds')::interval, '+91 •••••832', null, null, null, 'Google', null, null, 41, 13000, 'Microwave', 'seed.category.microwave', 'low', null, null, null, null, null, 'neutral', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-16', 'lks-ind', null, 35, 'history', 'answered', false, now() + ((-6048000000) || ' milliseconds')::interval, '+91 •••••960', null, null, null, 'Google', '1m 52s', 'inbound', 18, 2500, 'Accessories', 'seed.category.accessories', null, null, null, null, null, null, 'neutral', null, 'Warranty / service', 'seed.callReason.warrantyService', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-17', 'lks-ind', null, 36, 'history', 'missed', false, now() + ((-7603200000) || ' milliseconds')::interval, '+91 •••••301', null, null, null, 'SingleInterface', null, null, 34, 0, 'Service', 'seed.category.service', 'low', null, null, null, null, null, 'neutral', null, 'Delivery delay', 'seed.callReason.deliveryDelay', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-18', 'lks-ind', null, 37, 'history', 'answered', false, now() + ((-12096000000) || ' milliseconds')::interval, '+91 •••••487', null, null, null, 'Times of India', '5m 44s', 'inbound', 87, 54000, 'Air Conditioner', 'seed.category.airConditioner', null, null, null, null, null, null, 'positive', null, 'Price enquiry', 'seed.callReason.priceEnquiry', 'converted', true, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('ch-19', 'lks-ind', null, 38, 'history', 'missed', false, now() + ((-21600000000) || ' milliseconds')::interval, '+91 •••••712', null, null, null, 'Facebook', null, null, 52, 27000, 'Refrigerator', 'seed.category.refrigerator', 'medium', null, null, null, null, null, 'neutral', null, 'EMI options', 'seed.callReason.emiOptions', 'lost', false, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

-- ---------------- call transcript turns ----------------
insert into call_transcript_turns (call_id, turn_index, speaker, body, at_offset_ms) values
  ('cc-01', 1, 'manager', 'Lakshmi Electronics, Indiranagar. Good afternoon, how can I help you?', 0),
  ('cc-01', 2, 'customer', 'Hi. I saw you have the Samsung 1.5 ton inverter AC. What is the price on that right now?', 8000),
  ('cc-01', 3, 'manager', 'The 1.5 ton inverter 3-star is ₹38,000 including standard installation. The 5-star one is ₹44,500.', 18000),
  ('cc-01', 4, 'customer', 'That is a bit more than I planned. Do you have EMI on it?', 34000),
  ('cc-01', 5, 'manager', 'Yes — no-cost EMI for six months on most cards. On the 3-star that comes to about ₹6,350 a month.', 48000),
  ('cc-01', 6, 'customer', 'Okay, that is manageable. Is it in stock? I need it installed this week, the old one has completely died.', 72000),
  ('cc-01', 7, 'manager', 'We have three units. If you book by Friday we can install Saturday morning.', 96000),
  ('cc-01', 8, 'customer', 'Perfect. I will come Friday evening, around 5 or 6, after work. Can you keep one aside?', 130000),
  ('cc-01', 9, 'manager', 'Of course. I will note it down — Samsung 1.5 ton inverter, 3-star, held till Friday. May I have a name?', 165000),
  ('cc-01', 10, 'customer', 'I will call from this number when I start out. Keep it ready, that is all.', 205000),
  ('cc-01', 11, 'manager', 'Will do. See you Friday, sir.', 250000),
  ('cc-02', 1, 'manager', 'Hello, am I speaking with the caller who rang about the Times of India offer? This is Rajesh from Lakshmi Electronics.', 0),
  ('cc-02', 2, 'customer', 'Yes, yes. I called in the morning but nobody picked up.', 9000),
  ('cc-02', 3, 'manager', 'Apologies for that — we were with customers. You were asking about the 55-inch LG?', 16000),
  ('cc-02', 4, 'customer', 'Correct. The OLED one in the advertisement. Is that price genuine?', 24000),
  ('cc-02', 5, 'manager', 'It is. ₹1,09,990 for the C-series 55-inch OLED, and that includes wall mounting.', 32000),
  ('cc-02', 6, 'customer', 'And the older model? My brother said there is a cheaper one.', 45000),
  ('cc-02', 7, 'manager', 'There is a 2023 panel at ₹94,000. Honestly, for the difference I would suggest the newer one — better panel and three-year warranty.', 53000),
  ('cc-02', 8, 'customer', 'Can you send me the details? I will show my wife.', 70000),
  ('cc-02', 9, 'manager', 'I will WhatsApp the catalogue to this number right now.', 76000),
  ('cc-02', 10, 'customer', 'Good. We will come Saturday morning to see it in person.', 84000),
  ('cc-02', 11, 'manager', 'Saturday works. Come before noon, the showroom is quieter then.', 92000),
  ('cc-02', 12, 'customer', 'Done. Thank you.', 108000),
  ('cc-03', 1, 'manager', 'Lakshmi Electronics, good morning.', 0),
  ('cc-03', 2, 'customer', 'Hi. Do you have double-door refrigerators under 40,000?', 5000),
  ('cc-03', 3, 'manager', 'Several. Whirlpool, Samsung and LG all have 240 to 265 litre models in that range.', 12000),
  ('cc-03', 4, 'customer', 'Which one would you say is best? I am comparing online also.', 22000),
  ('cc-03', 5, 'manager', 'Depends on usage. The LG at ₹38,500 has the better compressor warranty — ten years. The Samsung at ₹36,000 is more energy efficient.', 30000),
  ('cc-03', 6, 'customer', 'Online I am seeing the LG for ₹36,900.', 62000),
  ('cc-03', 7, 'manager', 'That is possible, but that price usually excludes installation and the old-fridge exchange. With exchange we can come to ₹34,000.', 78000),
  ('cc-03', 8, 'customer', 'Okay. I need to discuss with my family first.', 120000),
  ('cc-03', 9, 'manager', 'Take your time. Shall I hold the exchange quote for a week?', 150000),
  ('cc-03', 10, 'customer', 'Yes, do that. I will decide by next week.', 180000),
  ('cc-03', 11, 'manager', 'I will note it down. Thank you for calling.', 210000),
  ('cc-04', 1, 'manager', 'Good morning sir, Rajesh calling from Lakshmi Electronics about your air conditioner service.', 0),
  ('cc-04', 2, 'customer', 'Finally. Do you know how many times I have called? Three weeks now.', 7000),
  ('cc-04', 3, 'manager', 'I understand, and I am sorry. I can see the installation was booked on the 12th.', 14000),
  ('cc-04', 4, 'customer', 'Booked, yes. Nobody came. Twice they said today, today. I took leave from office for nothing.', 22000),
  ('cc-04', 5, 'manager', 'That should not have happened. I am escalating this to the service desk myself today.', 33000),
  ('cc-04', 6, 'customer', 'That is what the last person also said.', 41000),
  ('cc-04', 7, 'manager', 'This time I am giving you my word — someone will call you within 24 hours with a fixed slot. If they do not, call this number and ask for me directly.', 46000),
  ('cc-04', 8, 'customer', 'Fine. But this is the last time I am waiting.', 58000),
  ('cc-05', 1, 'manager', 'Lakshmi Electronics, good morning.', 0),
  ('cc-05', 2, 'customer', 'Hello! Do you have the Sony WH-1000XM5 headphones?', 4000),
  ('cc-05', 3, 'manager', 'We do, in black and silver. ₹26,990.', 11000),
  ('cc-05', 4, 'customer', 'Oh. Amazon has it for around 24.', 18000),
  ('cc-05', 5, 'manager', 'During sale periods, yes. We are at ₹24,990 this month with the festive offer — and you get the store warranty and can test them before buying.', 24000),
  ('cc-05', 6, 'customer', 'That is actually good. Do you have any student discount? I have a college ID.', 38000),
  ('cc-05', 7, 'manager', 'Bring the ID and I will see what I can do on the accessories — a case or a stand.', 47000),
  ('cc-05', 8, 'customer', 'Nice. I will come this weekend to try them.', 56000),
  ('cc-05', 9, 'manager', 'Please do. Ask for Rajesh at the audio counter.', 62000),
  ('cc-05', 10, 'customer', 'Thank you!', 78000),
  ('cc-06', 1, 'customer', 'Congratulations! Your number has been selected for a pre-approved personal loan of up to ten lakh rupees. Press one to speak to—', 0),
  ('cc-06', 2, 'manager', 'Not interested.', 11000),
  ('cc-07', 1, 'manager', 'Good evening, is this Anand sir? Rajesh from Lakshmi Electronics — you called earlier this evening.', 0),
  ('cc-07', 2, 'customer', 'Yes! I called around quarter to seven, the shop line was busy.', 8000),
  ('cc-07', 3, 'manager', 'Sorry about that, evenings get hectic. You were looking at washing machines?', 15000),
  ('cc-07', 4, 'customer', 'Yes, front load. Around 7 kg. My wife wants the LG one she saw at her sister’s place.', 22000),
  ('cc-07', 5, 'manager', 'The LG 7kg front load — good machine. We have it at ₹32,500 with the inverter motor, ten year warranty on the motor.', 33000),
  ('cc-07', 6, 'customer', 'Her sister paid 34-something last year I think.', 48000),
  ('cc-07', 7, 'manager', 'Prices came down after the new model came in. Same machine, current stock.', 55000),
  ('cc-07', 8, 'customer', 'Okay. And delivery? We are in HAL 2nd stage.', 88000),
  ('cc-07', 9, 'manager', 'Free delivery there. If you confirm today I can put you on Saturday’s route — 10 AM slot.', 120000),
  ('cc-07', 10, 'customer', 'Saturday morning is perfect, we are home.', 150000),
  ('cc-07', 11, 'manager', 'Shall I book it then? ₹32,500, delivery Saturday 10 AM, installation same day.', 180000),
  ('cc-07', 12, 'customer', 'Yes, book it. I will pay on delivery — card is fine?', 220000),
  ('cc-07', 13, 'manager', 'Card, UPI, whatever is convenient. I will send the confirmation on WhatsApp.', 250000),
  ('cc-07', 14, 'customer', 'Very good. Thank you Rajesh.', 290000),
  ('cc-07', 15, 'manager', 'Thank you sir, see you Saturday.', 305000),
  ('ch-02', 1, 'manager', 'Lakshmi Electronics, good evening.', 0),
  ('ch-02', 2, 'customer', 'I want to know about EMI on the 65-inch Sony. The one for around 1,20,000.', 4000),
  ('ch-02', 3, 'manager', 'No-cost EMI is available up to nine months on HDFC and ICICI cards. Nine months works out to about ₹13,300.', 13000),
  ('ch-02', 4, 'customer', 'And if I pay full?', 40000),
  ('ch-02', 5, 'manager', 'Full payment I can do ₹1,17,500 and throw in the wall mount.', 50000),
  ('ch-02', 6, 'customer', 'Done. I will come tomorrow with my card.', 90000),
  ('ch-02', 7, 'manager', 'I will keep one aside for you.', 120000),
  ('ch-04', 1, 'customer', 'My washing machine was supposed to come Tuesday. It is Thursday.', 0),
  ('ch-04', 2, 'manager', 'Let me check the docket. I am sorry, sir — I can see the vehicle broke down on the Tuesday route.', 6000),
  ('ch-04', 3, 'customer', 'Nobody informed me. I waited the whole day.', 20000),
  ('ch-04', 4, 'manager', 'You are right, we should have called. I can get it to you tomorrow morning first slot, and I will waive the installation charge.', 28000),
  ('ch-04', 5, 'customer', 'Tomorrow morning definitely?', 55000),
  ('ch-04', 6, 'manager', 'Definitely. I am putting it as first delivery, and I will call you myself when the vehicle leaves.', 62000),
  ('ch-04', 7, 'customer', 'Okay then.', 130000),
  ('ch-06', 1, 'customer', 'I bought a split AC from you last week. When can you install?', 0),
  ('ch-06', 2, 'manager', 'Let me pull up the bill. Yes — the Voltas 1.5 ton. Installation team can come Sunday morning.', 5000),
  ('ch-06', 3, 'customer', 'Sunday is good. Do I need to buy the copper pipe separately?', 22000),
  ('ch-06', 4, 'manager', 'Standard three metres is included. Beyond that it is ₹450 a metre — the technician will measure and tell you before starting.', 35000),
  ('ch-06', 5, 'customer', 'Fine. What time Sunday?', 70000),
  ('ch-06', 6, 'manager', 'Between 9 and 11. He will call before coming.', 95000),
  ('ch-06', 7, 'customer', 'Thank you, that is very helpful.', 180000),
  ('ch-08', 1, 'customer', 'Do you have the boAt Rockerz 550?', 0),
  ('ch-08', 2, 'manager', 'That particular model we stopped stocking. We have the 551 and the JBL equivalent.', 4000),
  ('ch-08', 3, 'customer', 'No, I want the 550 only. My friend has it.', 14000),
  ('ch-08', 4, 'manager', 'I can order it, takes about four days.', 22000),
  ('ch-08', 5, 'customer', 'Four days is too long, I will check elsewhere.', 40000),
  ('ch-08', 6, 'manager', 'Understood. If you change your mind, do call.', 48000),
  ('ch-10', 1, 'manager', 'Sir, calling about the refrigerator complaint you registered.', 0),
  ('ch-10', 2, 'customer', 'Yes. It is still not cooling properly. Second technician also came and went.', 5000),
  ('ch-10', 3, 'manager', 'The compressor is under warranty for ten years, so any replacement is free. What did the technician write?', 16000),
  ('ch-10', 4, 'customer', 'He said gas. But he said gas last time also and charged me 1,800.', 34000),
  ('ch-10', 5, 'manager', 'You should not have been charged if it is a warranty repair. Send me that receipt on WhatsApp and I will get it refunded.', 48000),
  ('ch-10', 6, 'customer', 'I will send. But please send a senior person this time.', 80000),
  ('ch-10', 7, 'manager', 'I will request the area service manager directly.', 120000),
  ('ch-12', 1, 'manager', 'Good afternoon, calling back regarding your enquiry on the Samsung QLED.', 0),
  ('ch-12', 2, 'customer', 'Yes, the 65-inch. What is your best price?', 7000),
  ('ch-12', 3, 'manager', 'Listed at ₹92,000. For you, ₹88,000 with the soundbar bundled.', 14000),
  ('ch-12', 4, 'customer', 'Croma quoted 89 without soundbar.', 45000),
  ('ch-12', 5, 'manager', 'Then take ours — same panel, and the soundbar alone is worth 12,000.', 60000),
  ('ch-12', 6, 'customer', 'Alright. Can you deliver this Sunday?', 150000),
  ('ch-12', 7, 'manager', 'Sunday afternoon, and the installation team comes with it.', 200000),
  ('ch-12', 8, 'customer', 'Book it.', 300000),
  ('ch-14', 1, 'customer', 'Summer is starting, I need an AC installed before the heat.', 0),
  ('ch-14', 2, 'manager', 'Which size? Room dimensions?', 6000),
  ('ch-14', 3, 'customer', 'Bedroom, about 12 by 12.', 12000),
  ('ch-14', 4, 'manager', 'One ton is enough for that. The Daikin at ₹39,000 is what I would recommend — quiet, and their service is reliable here.', 20000),
  ('ch-14', 5, 'customer', 'Installation included?', 60000),
  ('ch-14', 6, 'manager', 'Included. We can do it this week.', 70000),
  ('ch-14', 7, 'customer', 'Let us do it.', 140000),
  ('ch-16', 1, 'customer', 'The remote for the TV I bought from you stopped working. Is it in warranty?', 0),
  ('ch-16', 2, 'manager', 'Remotes are covered for one year. When did you buy?', 6000),
  ('ch-16', 3, 'customer', 'Two years back I think.', 14000),
  ('ch-16', 4, 'manager', 'Then it would be a paid replacement — around ₹700 for the original, or ₹250 for a universal one.', 20000),
  ('ch-16', 5, 'customer', 'I will think about it.', 55000),
  ('ch-18', 1, 'customer', 'I saw your Republic Day advertisement. Two ACs, what is the offer?', 0),
  ('ch-18', 2, 'manager', 'On two units we can do 10 percent off the second one, plus free installation on both.', 8000),
  ('ch-18', 3, 'customer', 'Both 1.5 ton, same model.', 40000),
  ('ch-18', 4, 'manager', 'Then ₹54,000 for the pair, installed.', 55000),
  ('ch-18', 5, 'customer', 'That is fair. My wife will come tomorrow to finalise.', 200000),
  ('ch-18', 6, 'manager', 'I will keep the quote noted under this number.', 300000);

-- ---------------- reviews ----------------
insert into reviews (id, store_id, customer_id, seq, author_name, rating, body, platform, at, time_label, priority, removed_from_google, removed_at, edited, edited_at, previous_rating, tags) values
  ('rv-01', 'lks-ind', null, 1, 'Arjun Mehta', 5, 'Best electronics store in Indiranagar. Rajesh sir patiently helped me pick a TV under budget. Free delivery too!', 'Google', now() + ((-7200000) || ' milliseconds')::interval, '2h ago', false, false, null, false, null, null, array['staff', 'pricing', 'delivery']::text[]),
  ('rv-02', 'lks-ind', null, 2, 'Sneha Pillai', 5, 'Bought a Samsung fridge — staff explained EMI clearly, no hidden charges. Highly recommended.', 'Google', now() + ((-18000000) || ' milliseconds')::interval, '5h ago', false, false, null, false, null, null, array['staff', 'pricing']::text[]),
  ('rv-07', 'lks-ind', 'cust-019', 3, 'Prakash Menon', 1, 'Called four times about my AC installation. Nobody picks up the phone. Very poor after-sales.', 'Google', now() + ((-28800000) || ' milliseconds')::interval, '8h ago', true, false, null, false, null, null, array['service', 'installation']::text[]),
  ('rv-08', 'lks-ind', null, 4, 'Nithya Balan', 5, null, 'Google', now() + ((-39600000) || ' milliseconds')::interval, '11h ago', false, false, null, false, null, null, '{}'::text[]),
  ('rv-03', 'lks-ind', null, 5, 'Mohammed Faiz', 4, 'Good selection and pricing. Only minor issue was delivery slot — promised 10 AM, actually came at 1 PM. Otherwise great.', 'Google', now() + ((-93600000) || ' milliseconds')::interval, 'Yesterday', false, false, null, false, null, null, array['delivery', 'pricing']::text[]),
  ('rv-04', 'lks-ind', null, 6, 'Karthik N.', 2, 'Air conditioner installation was delayed by 3 days. Had to follow up multiple times. Product is fine but service needs to improve.', 'Google', now() + ((-108000000) || ' milliseconds')::interval, 'Yesterday', true, false, null, false, null, null, array['service', 'installation']::text[]),
  ('rv-09', 'lks-ind', null, 7, 'Ramesh Gowda', 3, 'Prices are okay, nothing special. Staff was busy with other customers.', 'Google', now() + ((-144000000) || ' milliseconds')::interval, 'Yesterday', false, false, null, false, null, null, array['pricing', 'staff']::text[]),
  ('rv-05', 'lks-ind', null, 8, 'Divya Krishnamurthy', 5, 'Bought my mom a microwave. Demo was thorough and store team installed it the same day. Lovely experience.', 'Justdial', now() + ((-180000000) || ' milliseconds')::interval, '2 days ago', false, false, null, false, null, null, array['staff', 'installation', 'storeExperience']::text[]),
  ('rv-10', 'lks-ind', null, 9, 'Suhas Kamath', 4, 'Updating my review — the service manager called and sorted out the gas refill at no charge. Took a while but they did make it right.', 'Google', now() + ((-208800000) || ' milliseconds')::interval, '2 days ago', false, false, null, true, now() + ((-208800000) || ' milliseconds')::interval, 2, array['service', 'staff']::text[]),
  ('rv-06', 'lks-ind', 'cust-775', 10, 'Anand Rao', 5, 'Honest pricing, no upselling pressure. Vikram on the floor was very knowledgeable about laptops.', 'Google', now() + ((-14160000) || ' milliseconds')::interval, '4h ago', false, false, null, false, null, null, array['staff', 'pricing']::text[]),
  ('rv-11', 'lks-ind', null, 11, 'Meera Iyer', 5, 'Delivery came exactly in the promised slot and the installation boy cleaned up after himself. Small thing, but rare.', 'Google', now() + ((-424800000) || ' milliseconds')::interval, '5 days ago', false, false, null, false, null, null, array['delivery', 'installation']::text[]),
  ('rv-12', 'lks-ind', null, 12, 'Joseph Thomas', 4, null, 'Google', now() + ((-604800000) || ' milliseconds')::interval, '7 days ago', false, false, null, false, null, null, '{}'::text[]),
  ('rv-13', 'lks-ind', null, 13, 'Deals Hub', 1, 'Worst shop, everything overpriced, go to our store in Koramangala instead for genuine rates, call 98xxxxxx.', 'Google', now() + ((-777600000) || ' milliseconds')::interval, '9 days ago', false, true, now() + ((-604800000) || ' milliseconds')::interval, false, null, null, '{}'::text[]),
  ('rv-14', 'lks-ind', null, 14, 'Shalini Rao', 5, 'Second appliance I have bought here. They remember you, and that counts for something.', 'Google', now() + ((-1036800000) || ' milliseconds')::interval, '12 days ago', false, false, null, false, null, null, array['staff', 'storeExperience']::text[]),
  ('rv-15', 'lks-ind', null, 15, 'Vinod Shetty', 2, 'Washing machine developed a noise in two weeks. Service visit took five days to arrange.', 'Google', now() + ((-1382400000) || ' milliseconds')::interval, '16 days ago', false, false, null, false, null, null, array['service', 'productQuality']::text[]),
  ('rv-16', 'lks-ind', null, 16, 'Fatima Sheikh', 5, 'Very patient staff. I asked the same questions three times and nobody made me feel stupid.', 'Google', now() + ((-1814400000) || ' milliseconds')::interval, '21 days ago', false, false, null, false, null, null, array['staff']::text[]),
  ('rv-17', 'lks-ind', null, 17, 'Girish Hegde', 4, null, 'Google', now() + ((-2246400000) || ' milliseconds')::interval, '26 days ago', false, false, null, false, null, null, '{}'::text[]),
  ('rv-18', 'lks-ind', null, 18, 'Aparna Desai', 5, 'Got a better price here than the online sale, and they matched the exchange value on my old TV.', 'Google', now() + ((-2937600000) || ' milliseconds')::interval, 'Last month', false, false, null, false, null, null, array['pricing']::text[]),
  ('rv-19', 'lks-ind', null, 19, 'Sanjay Bhatt', 3, 'Decent store. Parking is a nightmare on 100 Feet Road though.', 'Google', now() + ((-3888000000) || ' milliseconds')::interval, 'Last month', false, false, null, false, null, null, array['storeExperience']::text[]),
  ('rv-20', 'lks-ind', null, 20, 'Lakshmi Narayan', 5, 'Been buying from this shop since it opened. Never had a reason to go anywhere else.', 'Google', now() + ((-5356800000) || ' milliseconds')::interval, '2 months ago', false, false, null, false, null, null, array['storeExperience', 'staff']::text[]),
  ('rv-21', 'lks-ind', null, 21, 'Harish Kulkarni', 4, 'Good store, fair prices. Wish they stocked more of the premium audio brands.', 'Google', now() + ((-9504000000) || ' milliseconds')::interval, '4 months ago', false, false, null, false, null, null, array['pricing', 'productQuality']::text[]);

-- ---------------- review replies (history, including deleted ones) ----------------
insert into review_replies (id, review_id, platform, body, author, at, deleted, deleted_at) values
  ('rp-05-1', 'rv-05', 'justdial', 'Thank you so much, Divya! It means a lot that we could make this special for your mom. Looking forward to serving you again. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-165600000) || ' milliseconds')::interval, false, null),
  ('rp-10-1', 'rv-10', 'gbp', 'Thank you for updating this, Suhas — and for your patience while we got to the bottom of it. The refill should hold now; if anything changes, call the store and ask for me directly. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-198000000) || ' milliseconds')::interval, false, null),
  ('rp-06-1', 'rv-06', 'gbp', 'Thank you, Anand! We will pass on the kind words to Vikram. Enjoy your new laptop, and do come back any time you need accessories. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-10800000) || ' milliseconds')::interval, false, null),
  ('rp-11-1', 'rv-11', 'gbp', 'Thank you, Meera — we will make sure the delivery team hears this. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-417600000) || ' milliseconds')::interval, false, null),
  ('rp-13-1', 'rv-13', 'gbp', 'We have no record of a purchase against this name and this review appears to advertise another business. We have reported it to Google. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-705600000) || ' milliseconds')::interval, true, now() + ((-604800000) || ' milliseconds')::interval),
  ('rp-14-1', 'rv-14', 'gbp', 'Thank you for your feedback. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-1033200000) || ' milliseconds')::interval, true, now() + ((-936000000) || ' milliseconds')::interval),
  ('rp-14-2', 'rv-14', 'gbp', 'Shalini, thank you — and yes, we do remember! Thank you for coming back to us a second time. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-928800000) || ' milliseconds')::interval, false, null),
  ('rp-16-1', 'rv-16', 'gbp', 'Thank you, Fatima — questions are what we are here for. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-1785600000) || ' milliseconds')::interval, false, null),
  ('rp-18-1', 'rv-18', 'gbp', 'Thank you, Aparna! Do bring the old TV documents when you visit next — we can process the exchange credit then. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-2844000000) || ' milliseconds')::interval, false, null),
  ('rp-20-1', 'rv-20', 'gbp', 'Thank you for staying with us all these years. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-5338800000) || ' milliseconds')::interval, false, null),
  ('rp-21-1', 'rv-21', 'gbp', 'Noted, Harish — we are expanding the audio section this year. Do come and take a look. — Team Lakshmi Electronics, Indiranagar', 'Rajesh Kumar', now() + ((-9460800000) || ' milliseconds')::interval, false, null);

-- ---------------- media assets ----------------
insert into media_assets (id, store_id, seq, kind, label, label_key, tag, tag_key, src) values
  ('mm-cover', 'lks-ind', 1, 'cover', 'Storefront', 'seed.media.storefront', 'Cover photo', 'seed.media.coverPhoto', null),
  ('mm-01', 'lks-ind', 2, 'photo', 'AC display wall', 'seed.media.acDisplayWall', null, null, null),
  ('mm-02', 'lks-ind', 3, 'photo', 'Billing counter', 'seed.media.billingCounter', null, null, null),
  ('mm-03', 'lks-ind', 4, 'photo', 'TV zone', 'seed.media.tvZone', null, null, null),
  ('mm-04', 'lks-ind', 5, 'photo', 'selfie_with_team_diwali.jpg', null, null, null, null),
  ('mm-05', 'lks-ind', 6, 'photo', 'Croma_Koramangala_offer_board.jpg', null, null, null, null),
  ('mm-06', 'lks-ind', 7, 'photo', 'WhatsApp Image 2026-06-28 at 7.14.02 PM.jpeg', null, null, null, null),
  ('mm-07', 'lks-ind', 8, 'photo', 'cousin_wedding_reception.jpg', null, null, null, null),
  ('mm-08', 'lks-ind', 9, 'photo', 'IMG_20260612_113045.jpg', null, null, null, null);

-- ---------------- post templates ----------------
insert into post_templates (id, seq, type, name, name_key, icon, accent, headline, headline_key, cta, cta_key) values
  ('pt-standard', 1, 'standard', 'Standard', 'seed.post.nameStandard', 'Sparkles', '#0070FC', 'What’s New', 'seed.post.headlineStandard', 'Learn More', 'seed.post.ctaStandard'),
  ('pt-offer', 2, 'offer', 'Offer', 'seed.post.nameOffer', 'Wallet', '#16A34A', 'Special Offer', 'seed.post.headlineOffer', 'Redeem Offer', 'seed.post.ctaOffer'),
  ('pt-event', 3, 'event', 'Event', 'seed.post.nameEvent', 'PartyPopper', '#F97316', 'You’re Invited', 'seed.post.headlineEvent', 'Book Now', 'seed.post.ctaEvent'),
  ('pt-testimonial', 4, 'testimonial', 'Testimonial', 'seed.post.nameTestimonial', 'MessageSquareQuote', '#0E0071', 'Customer Story', 'seed.post.headlineTestimonial', 'Read More', 'seed.post.ctaTestimonial');

commit;

-- ============================================================
-- SANITY CHECK — expected row counts (from the seed arrays at generation time):
--
--   dealers                    3
--   stores                     5
--   managers                   3
--   customers                  11
--   customer_timeline_events   21
--   customer_notes             8
--   calls                      38
--   call_transcript_turns      129
--   reviews                    21
--   review_replies             11
--   media_assets               9
--   post_templates             4
--   access_requests            0
--
-- Verify with:
--   select 'dealers' t, count(*) from dealers
--   union all select 'stores', count(*) from stores
--   union all select 'managers', count(*) from managers
--   union all select 'customers', count(*) from customers
--   union all select 'customer_timeline_events', count(*) from customer_timeline_events
--   union all select 'customer_notes', count(*) from customer_notes
--   union all select 'calls', count(*) from calls
--   union all select 'call_transcript_turns', count(*) from call_transcript_turns
--   union all select 'reviews', count(*) from reviews
--   union all select 'review_replies', count(*) from review_replies
--   union all select 'media_assets', count(*) from media_assets
--   union all select 'post_templates', count(*) from post_templates
--   union all select 'access_requests', count(*) from access_requests
--   ;
-- ============================================================
