// ============================================================
// i18n NATIVE RUNTIME — the counterpart to apps/web/src/i18n/index.js.
//
// The catalogs and the language registry are NOT duplicated here: both are imported
// from @connect/core, so a string added for mobile lands in the same 13 catalogs the
// web reads (EXPO-MIGRATION.md §6, "one catalog set"). What differs is only the
// platform plumbing, which is why this file exists at all rather than being shared:
//
//   web                             native
//   ─────────────────────────────   ─────────────────────────────────────────────
//   <link> a Noto webfont           expo-font, loaded per script (Phase 5)
//   <html dir> per container        I18nManager.forceRTL + reload (sharp edge #5)
//   localStorage                    the core storage facade (AsyncStorage-backed)
//   navigator.language              the device locale (Phase 5, expo-localization)
//
// Only English is bundled eagerly; every other catalog is a lazy import through core's
// generated CATALOGS map — the same map, generated by scripts/gen-locale-index.mjs
// precisely so Metro can bundle what Vite's import.meta.glob used to resolve.
// ============================================================
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import en from '@connect/core/locales/en/common.json'
import { DEFAULT_LANGUAGE, LANGUAGE_CODES, getLanguage } from '@connect/core/i18n/languages.js'
import { CATALOGS } from '@connect/core/locales/index.js'
import { storage } from '@connect/core/storage.js'

const STORAGE_KEY = 'si-lang'
const NS = 'common'

/**
 * The language to boot with: the dealer's saved choice, else English.
 *
 * Reads through the CORE facade rather than AsyncStorage directly — by the time this
 * runs the boot gate has already preloaded the cache, so the read is synchronous and
 * the saved language is applied before the first frame rather than flashing English.
 */
export function initialLanguage() {
  const saved = storage.getItem(STORAGE_KEY)
  return saved && LANGUAGE_CODES.includes(saved) ? saved : DEFAULT_LANGUAGE
}

async function loadCatalog(code) {
  if (code === DEFAULT_LANGUAGE) return en
  const loader = CATALOGS[code]
  if (!loader) return null
  try {
    const mod = await loader()
    return mod.default || mod
  } catch {
    return null // catalog not generated yet → English, exactly as on web
  }
}

/** Switch language: fetch the catalog if it is not loaded, then swap strings. */
export async function setLanguage(code) {
  const lang = getLanguage(code)
  if (!i18n.hasResourceBundle(lang.code, NS)) {
    const catalog = await loadCatalog(lang.code)
    if (catalog) i18n.addResourceBundle(lang.code, NS, catalog, true, true)
  }
  await i18n.changeLanguage(lang.code)
  storage.setItem(STORAGE_KEY, lang.code)
  return lang
}

export function currentLanguage() {
  return getLanguage(i18n.resolvedLanguage || i18n.language || DEFAULT_LANGUAGE)
}

/**
 * Initialise i18next. Awaited by the boot gate so the tree never renders against a
 * half-built catalog. Boots on English, then switches to the saved language — the
 * same two-step the web runtime uses, so the boot catalog is always present.
 */
export async function initI18n() {
  await i18n.use(initReactI18next).init({
    resources: { en: { [NS]: en } },
    lng: DEFAULT_LANGUAGE,
    fallbackLng: DEFAULT_LANGUAGE,
    defaultNS: NS,
    ns: [NS],
    interpolation: { escapeValue: false }, // React escapes already
    returnEmptyString: false,              // empty translation → English
    react: { useSuspense: false },         // no Suspense boundary in the boot gate
    compatibilityJSON: 'v4',               // Hermes-safe plural handling
  })

  const boot = initialLanguage()
  if (boot !== DEFAULT_LANGUAGE) await setLanguage(boot)
  return i18n
}

export default i18n
