// AUTO-GENERATED by scripts/gen-locale-index.mjs — do not edit by hand.
// Static lazy-loader map over the catalog dirs on disk. Replaces Vite-only
// import.meta.glob so Metro (Expo) can bundle the same catalogs in Phase 1.
// Languages in the registry without a generated catalog fall back to English
// at the call site, exactly as the glob (which only matched real files) did.
export const CATALOGS = {
  as: () => import('./as/common.json'),
  bn: () => import('./bn/common.json'),
  en: () => import('./en/common.json'),
  gu: () => import('./gu/common.json'),
  hi: () => import('./hi/common.json'),
  kn: () => import('./kn/common.json'),
  ml: () => import('./ml/common.json'),
  mr: () => import('./mr/common.json'),
  or: () => import('./or/common.json'),
  pa: () => import('./pa/common.json'),
  ta: () => import('./ta/common.json'),
  te: () => import('./te/common.json'),
  ur: () => import('./ur/common.json'),
}
